### ISSUE TITLE
checkFileStat() function can detect magisk when magisk hide enabled?

### ISSUE THREAD

**Issue by comomind** [KimChangYoun/rootbeerFresh#2] opened 2019-02-11 02:55 UTC
I tested rootbeerFresh in my nexus 6 with magisk 18.0. (magisk hide enabled) 

As my observation, uds_detect_count is working but magisk_file_detect is not. 

Q1. checkFileStat() function can detect when magisk hide enabled? 
Q2. As you mentioned in https://github.com/scottyab/rootbeer/pull/88#issuecomment-459619921 
  We already included stat header(sys/stat.h). 
  why extern stat function declaration is needed?

**Comment by KimChangYoun** [comment] 2019-02-11 08:28
@comomind 
A1. When I tested it on the Galaxy S6 Edge +, it was detected.
A2. In my case, I only need to extern the function.

The UDS detection method is clear. Therefore, it will work on most devices.
However, the way you use the Stat function can vary from device to device.
This is because the Stat command may not be supported or may not be accessible with the Stat command.

Please provide details of the model name and OS version of Nexus 6.

**Comment by KimChangYoun** [comment] 2019-03-19 09:08
I have recently confirmed that the stat () function does not work on all phones.

Therefore, it is recommended to use the existing Unix Domain Socket detection logic as it is.

I am going to modify this part sooner or later, and I am worried about separating the stat () detection logic separately.

**Comment by KimChangYoun** [comment] 2019-04-12 06:41
Existing logic has been found to be detected if either a UDS or Stat function detects a trace of Magisk.
Therefore, we will close the issue.
Thank you very much for your interest.

**Closed as completed by KimChangYoun** 2019-04-12 06:41 UTC
